services:
  - type: web
    name: time-tracking-app
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # これは手動で設定する必要があります
      - key: SESSION_SECRET
        generateValue: true # Renderが自動的に安全な値を生成します